# Generated by Django 6.0.8 on 2026-09-20 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_workspacequotadecision_workspacequotapolicy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('enterprise', 'Enterprise')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('individual_principal_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces_account',
            },
        ),
        migrations.CreateModel(
            name='AccountMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workspaces_accountmembership',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='uniq_default_workspace_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('individual', 'team', 'enterprise'))), name='account_kind_closed'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('individual_principal_uuid__isnull', False), ('kind', 'individual')), models.Q(('individual_principal_uuid__isnull', True), ('kind__in', ('team', 'enterprise'))), _connector='OR'), name='account_individual_principal_shape'),
        ),
        migrations.AddField(
            model_name='organization',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='workspaces.account'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('account',), name='uniq_default_organization_per_account'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('account__isnull', False), ('is_default', False), _connector='OR'), name='organization_default_requires_account'),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='workspaces.account'),
        ),
        migrations.AddConstraint(
            model_name='accountmembership',
            constraint=models.UniqueConstraint(fields=('account', 'principal_uuid'), name='uniq_account_principal_membership'),
        ),
    ]
