# Generated by Django 6.0.8 on 2026-09-20 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_account_accountmembership_organization_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationMutationFence',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('blocked_operation_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces_authorization_mutation_fence',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kind', models.CharField(choices=[('installation', 'Installation'), ('account', 'Account')], max_length=16)),
                ('account_uuid', models.UUIDField(blank=True, null=True)),
                ('organization_uuid', models.UUIDField(blank=True, null=True)),
                ('workspace_uuid', models.UUIDField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces_authorization_group',
                'constraints': [models.UniqueConstraint(fields=('scope_kind', 'account_uuid', 'organization_uuid', 'workspace_uuid', 'name'), name='uniq_authz_group_scope_name')],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('fence_key', models.CharField(db_index=True, max_length=64)),
                ('generation', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('denied', 'Denied'), ('unresolved', 'Unresolved')], db_index=True, max_length=16)),
                ('actor_uuid', models.UUIDField()),
                ('actor_kind', models.CharField(max_length=16)),
                ('relationship_kind', models.CharField(choices=[('action', 'Action assignment'), ('group_member', 'Group membership'), ('role_assign', 'Role assignment')], default='action', max_length=16)),
                ('subject_kind', models.CharField(max_length=16)),
                ('subject_uuid', models.UUIDField()),
                ('action', models.CharField(max_length=120)),
                ('effect', models.CharField(max_length=16)),
                ('target_kind', models.CharField(max_length=16)),
                ('target_uuid', models.UUIDField(blank=True, null=True)),
                ('scope_kind', models.CharField(max_length=16)),
                ('account_uuid', models.UUIDField(blank=True, null=True)),
                ('organization_uuid', models.UUIDField(blank=True, null=True)),
                ('workspace_uuid', models.UUIDField(blank=True, null=True)),
                ('model_id', models.CharField(max_length=64)),
                ('credential_digest', models.CharField(max_length=64)),
                ('outcome_reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces_authorization_operation',
                'constraints': [models.UniqueConstraint(fields=('fence_key', 'generation'), name='uniq_authz_fence_generation')],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kind', models.CharField(choices=[('installation', 'Installation'), ('account', 'Account')], max_length=16)),
                ('account_uuid', models.UUIDField(blank=True, null=True)),
                ('organization_uuid', models.UUIDField(blank=True, null=True)),
                ('workspace_uuid', models.UUIDField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('predefined_code', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces_authorization_policy',
                'constraints': [models.UniqueConstraint(fields=('scope_kind', 'account_uuid', 'organization_uuid', 'workspace_uuid', 'name'), name='uniq_authz_policy_scope_name')],
            },
        ),
    ]
