# Generated by Django 6.0.8 on 2026-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_authorizationmutationfence_authorizationgroup_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='authorizationgroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_uuid__isnull', True), ('organization_uuid__isnull', True), ('scope_kind', 'installation'), ('workspace_uuid__isnull', True)), models.Q(('account_uuid__isnull', False), ('scope_kind', 'account'), models.Q(('workspace_uuid__isnull', True), ('organization_uuid__isnull', False), _connector='OR')), _connector='OR'), name='authz_group_scope_shape'),
        ),
        migrations.AddConstraint(
            model_name='authorizationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_uuid__isnull', True), ('organization_uuid__isnull', True), ('scope_kind', 'installation'), ('workspace_uuid__isnull', True)), models.Q(('account_uuid__isnull', False), ('scope_kind', 'account'), models.Q(('workspace_uuid__isnull', True), ('organization_uuid__isnull', False), _connector='OR')), _connector='OR'), name='authz_policy_scope_shape'),
        ),
    ]
