# Generated by Django 6.0.8 on 2026-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_authorizationgroup_authz_group_scope_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationgroup',
            name='predefined_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='authorizationoperation',
            name='relationship_kind',
            field=models.CharField(choices=[('action', 'Action assignment'), ('group_member', 'Group membership'), ('role_assign', 'Role assignment'), ('predefined', 'Predefined role assignment')], default='action', max_length=16),
        ),
    ]
