# Generated by Django 6.0.8 on 2026-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_authorization_predefined_groups'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authorizationgroup',
            name='uniq_authz_group_scope_name',
        ),
        migrations.RemoveConstraint(
            model_name='authorizationpolicy',
            name='uniq_authz_policy_scope_name',
        ),
        migrations.AddField(
            model_name='authorizationoperation',
            name='reconcile_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='authorizationgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_kind', 'installation')), fields=('scope_kind', 'name'), name='uniq_authz_group_install_name'),
        ),
        migrations.AddConstraint(
            model_name='authorizationgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('organization_uuid__isnull', True), ('scope_kind', 'account')), fields=('scope_kind', 'account_uuid', 'name'), name='uniq_authz_group_account_name'),
        ),
        migrations.AddConstraint(
            model_name='authorizationgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('organization_uuid__isnull', False), ('scope_kind', 'account'), ('workspace_uuid__isnull', True)), fields=('scope_kind', 'account_uuid', 'organization_uuid', 'name'), name='uniq_authz_group_org_name'),
        ),
        migrations.AddConstraint(
            model_name='authorizationgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_kind', 'account'), ('workspace_uuid__isnull', False)), fields=('scope_kind', 'account_uuid', 'organization_uuid', 'workspace_uuid', 'name'), name='uniq_authz_group_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='authorizationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_kind', 'installation')), fields=('scope_kind', 'name'), name='uniq_authz_policy_install_name'),
        ),
        migrations.AddConstraint(
            model_name='authorizationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('organization_uuid__isnull', True), ('scope_kind', 'account')), fields=('scope_kind', 'account_uuid', 'name'), name='uniq_authz_policy_account_name'),
        ),
        migrations.AddConstraint(
            model_name='authorizationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('organization_uuid__isnull', False), ('scope_kind', 'account'), ('workspace_uuid__isnull', True)), fields=('scope_kind', 'account_uuid', 'organization_uuid', 'name'), name='uniq_authz_policy_org_name'),
        ),
        migrations.AddConstraint(
            model_name='authorizationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_kind', 'account'), ('workspace_uuid__isnull', False)), fields=('scope_kind', 'account_uuid', 'organization_uuid', 'workspace_uuid', 'name'), name='uniq_authz_policy_workspace_name'),
        ),
    ]
