# Generated by Django 6.0.8 on 2026-09-20 16:02

import hashlib
import json

from django.db import migrations, models


def populate_idempotency_namespaces(apps, schema_editor):
    operation_model = apps.get_model("workspaces", "AuthorizationOperation")
    for operation in operation_model.objects.all().iterator():
        payload = {
            "actor": str(operation.actor_uuid),
            "actor_kind": operation.actor_kind,
            "scope": {
                "kind": operation.scope_kind,
                "account": str(operation.account_uuid) if operation.account_uuid else None,
                "organization": str(operation.organization_uuid) if operation.organization_uuid else None,
                "workspace": str(operation.workspace_uuid) if operation.workspace_uuid else None,
            },
        }
        encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        operation.idempotency_namespace = hashlib.sha256(encoded).hexdigest()
        operation.save(update_fields=["idempotency_namespace"])


def clear_idempotency_namespaces(apps, schema_editor):
    operation_model = apps.get_model("workspaces", "AuthorizationOperation")
    operation_model.objects.update(idempotency_namespace=None)


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_authorization_recovery_and_scope_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationoperation',
            name='idempotency_namespace',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationoperation',
            name='idempotency_key',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(populate_idempotency_namespaces, clear_idempotency_namespaces),
        migrations.AlterField(
            model_name="authorizationoperation",
            name="idempotency_namespace",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='authorizationoperation',
            constraint=models.UniqueConstraint(fields=('idempotency_namespace', 'idempotency_key'), name='uniq_authz_idempotency_namespace_key'),
        ),
    ]
