# Generated by Django 6.0.8 on 2026-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_authorizationoperation_idempotency_namespace_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authorizationoperation',
            name='uniq_authz_fence_generation',
        ),
        migrations.AddConstraint(
            model_name='authorizationoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['requested', 'confirmed', 'unresolved'])), fields=('fence_key', 'generation'), name='uniq_authz_fence_generation'),
        ),
    ]
