# Generated by Django 6.0.8 on 2026-09-21 04:35

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def preserve_journal_attribution(apps, schema_editor):
    operations = apps.get_model("workspaces", "AuthorizationOperation").objects.using(schema_editor.connection.alias)
    if operations.filter(audit_actor_principal_uuid__isnull=False).exists():
        raise IrreversibleError("Cannot discard committed authorization actor attribution")


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0029_principal_audit_attribution"),
        ("workspaces", "0018_authorization_operation_provider_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizationoperation",
            name="audit_actor_principal_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_journal_attribution),
    ]
