# Generated by Django 6.0.6 on 2026-07-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0031_aces_content_delivery_binding'),
        ('engine', '0031_capacity_signaling'),
    ]

    operations = [
    ]
