# Generated by Django 6.0.8 on 2026-09-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0057_publicoperationretrybinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeCleanupVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True)),
                ('operation_id', models.UUIDField(db_index=True)),
                ('outcome', models.CharField(choices=[('VERIFIED_ABSENT', 'Verified absent'), ('RESIDUALS_FOUND', 'Residuals found'), ('INCOMPLETE', 'Incomplete inventory')], max_length=24)),
                ('scope', models.JSONField()),
                ('residual_categories', models.JSONField(default=list)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'engine_range_cleanup_verification',
                'indexes': [models.Index(fields=['request_id', 'created_at'], name='engine_cleanupver_req_idx')],
            },
        ),
    ]
