# Generated by Django 6.0.8 on 2026-09-16 01:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0067_publicoperationretrybinding_rangecleanupverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deployment_id", models.UUIDField()),
                ("request_id", models.UUIDField(db_index=True)),
                ("operation_id", models.UUIDField(db_index=True)),
                ("range_id", models.UUIDField(db_index=True)),
                ("draw_key", models.UUIDField(db_index=True)),
                ("workload_role", models.CharField(max_length=128)),
                ("intent_digest", models.CharField(max_length=71)),
                ("policy_digest", models.CharField(max_length=71)),
                ("alias_shards", models.JSONField()),
                ("snapshot", models.JSONField()),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(null=True)),
                ("unresolved_liabilities", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request_id", "operation_id", "workload_role"), name="model_allocation_operation_role"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelQuotaIdentity",
            fields=[
                ("identity", models.CharField(max_length=71, primary_key=True, serialize=False)),
                ("deployment_id", models.UUIDField(db_index=True)),
                ("provider_adapter_id", models.CharField(max_length=128)),
                ("provider_quota_identity", models.CharField(max_length=256)),
                ("dimension", models.CharField(max_length=128)),
                ("unit", models.CharField(max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment_id", "provider_adapter_id", "provider_quota_identity", "dimension", "unit"),
                        name="model_quota_real_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelCapacityReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_key", models.CharField(max_length=256)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("amount", models.PositiveBigIntegerField()),
                ("consumed", models.PositiveBigIntegerField(default=0)),
                ("released_at", models.DateTimeField(null=True)),
                ("observation", models.JSONField()),
                (
                    "assessment",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="engine.capacityassessment"),
                ),
                (
                    "quota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="engine.modelquotaidentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelAliasAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("logical_alias", models.CharField(max_length=128)),
                ("shard", models.JSONField()),
                ("policy_digest", models.CharField(max_length=71)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="engine.allocationgroup",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("group", "logical_alias"), name="model_group_alias_once")
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelAllocationAuthority",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision", models.PositiveBigIntegerField()),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorities",
                        to="engine.modelallocation",
                    ),
                ),
                (
                    "fence",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="engine.sharingauthorityfence"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("allocation", "fence"), name="model_allocation_fence_once")
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelCapacityDraw",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveBigIntegerField()),
                ("released_at", models.DateTimeField(null=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="draws", to="engine.modelallocation"
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draws",
                        to="engine.modelcapacityreservation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("allocation", "reservation"), name="model_draw_allocation_once"),
                    models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="model_draw_positive"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelPendingGrant",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("grant_epoch", models.PositiveBigIntegerField(default=1)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="grant", to="engine.modelallocation"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("grant_epoch__gt", 0)), name="model_grant_positive_epoch"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["pending", "revoked"])), name="model_grant_closed_state"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="modelcapacityreservation",
            index=models.Index(
                fields=["quota", "released_at", "window_start", "window_end"], name="model_quota_overlap"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcapacityreservation",
            constraint=models.UniqueConstraint(
                fields=("quota", "scope_key", "window_start", "window_end"), name="model_capacity_scope_window"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcapacityreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("consumed__lte", models.F("amount"))), name="model_capacity_draw_ceiling"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcapacityreservation",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="model_capacity_positive"),
        ),
        migrations.AddConstraint(
            model_name="modelcapacityreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("window_end__gt", models.F("window_start"))), name="model_capacity_window"
            ),
        ),
    ]
