# Generated by Django 6.0.8 on 2026-09-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0068_model_quota_allocations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelLaunchPreparationRecord",
            fields=[
                ("request_id", models.UUIDField(primary_key=True, serialize=False)),
                ("intent_digest", models.CharField(max_length=71)),
                ("intent", models.JSONField()),
                ("catalog", models.JSONField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelQuotaReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("catalog_digest", models.CharField(max_length=71)),
                ("quota_pool_id", models.CharField(max_length=128)),
                ("observed_at", models.DateTimeField()),
                ("observation", models.JSONField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog_digest", "quota_pool_id"), name="model_quota_reading_revision"
                    )
                ],
            },
        ),
    ]
