# Generated by Django 6.0.8 on 2026-09-17 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0068_runtimeplugininstallation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimePluginRangeBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pin", models.JSONField()),
                ("pin_digest", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="engine.runtimeplugininstallation"
                    ),
                ),
                ("range", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="engine.range")),
            ],
        ),
        migrations.CreateModel(
            name="RuntimePluginPackBinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("organization_uuid", models.UUIDField(db_index=True)),
                ("pack_id", models.CharField(max_length=100)),
                ("pack_digest", models.CharField(max_length=71)),
                ("bindings", models.JSONField()),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="engine.runtimeplugininstallation"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_uuid", "pack_id"), name="runtime_plugin_pack_binding"
                    )
                ],
            },
        ),
    ]
