# Generated by Django 6.0.8 on 2026-09-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0069_model_launch_preparation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelOptionalAbsence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField()),
                ("operation_id", models.UUIDField()),
                ("workload_role", models.CharField(max_length=128)),
                ("intent_digest", models.CharField(max_length=71)),
                ("reason", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request_id", "operation_id", "workload_role"), name="model_optional_operation_role"
                    )
                ],
            },
        ),
    ]
