# Generated by Django 6.0.8 on 2026-09-17 01:29

from django.db import migrations, models


def grant_projection_read(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "GRANT SELECT (id, operation_id, state, input_digest, result) "
            "ON engine_runtime_plugin_invocation TO provisioner_lambda"
        )


def revoke_projection_read(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "REVOKE SELECT (id, operation_id, state, input_digest, result) "
            "ON engine_runtime_plugin_invocation FROM provisioner_lambda"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0069_runtime_plugin_bindings"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimePluginInvocation",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("operation_id", models.UUIDField(db_index=True)),
                ("request_id", models.UUIDField()),
                ("phase", models.CharField(max_length=16)),
                ("input", models.JSONField()),
                ("input_digest", models.CharField(max_length=71)),
                ("result", models.JSONField(null=True)),
                ("state", models.CharField(db_index=True, default="pending", max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "engine_runtime_plugin_invocation",
                "constraints": [
                    models.UniqueConstraint(fields=("operation_id", "phase"), name="runtime_plugin_operation_phase"),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["pending", "planned", "failed"])),
                        name="runtime_plugin_invocation_state",
                    ),
                ],
            },
        ),
        migrations.RunPython(grant_projection_read, revoke_projection_read),
    ]
