# Generated by Django 6.0.8 on 2026-09-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0070_model_optional_absence"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcapacityreservation",
            name="workload_budgets",
            field=models.JSONField(default=dict),
        ),
    ]
