# Generated by Django 6.0.8 on 2026-09-17 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0071_model_workload_budgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBudgetAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deployment_id', models.UUIDField(db_index=True)),
                ('account_ref', models.CharField(max_length=128)),
                ('dimension', models.CharField(max_length=16)),
                ('unit', models.CharField(max_length=64)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('limit', models.PositiveBigIntegerField()),
                ('spent', models.PositiveBigIntegerField(default=0)),
                ('reserved', models.PositiveBigIntegerField(default=0)),
                ('requests', models.PositiveBigIntegerField(default=0)),
                ('active_leases', models.PositiveBigIntegerField(default=0)),
                ('definition_revision', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelBudgetPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held', models.PositiveBigIntegerField()),
                ('settled', models.PositiveBigIntegerField(default=0)),
                ('state', models.CharField(default='held', max_length=16)),
                ('definition_revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDispatchLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_token', models.CharField(max_length=64)),
                ('dispatch_deadline', models.DateTimeField()),
                ('continuation_revision', models.PositiveBigIntegerField(default=0)),
                ('continuation_deadline', models.DateTimeField(null=True)),
                ('transport_status', models.CharField(default='dispatching', max_length=16)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelReconciliationObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_request_ref', models.CharField(blank=True, default='', max_length=256)),
                ('next_attempt_at', models.DateTimeField()),
                ('outcome', models.CharField(default='unknown', max_length=16)),
                ('last_observation', models.JSONField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRequestReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation_id', models.UUIDField(db_index=True)),
                ('grant_epoch', models.PositiveBigIntegerField()),
                ('logical_alias', models.CharField(max_length=128)),
                ('shard', models.JSONField()),
                ('caller_key_hmac', models.CharField(blank=True, default='', max_length=71)),
                ('key_version', models.CharField(blank=True, default='', max_length=32)),
                ('intent_fingerprint_hmac', models.CharField(blank=True, default='', max_length=71)),
                ('intent_contract_version', models.CharField(blank=True, default='', max_length=64)),
                ('reservation_vector', models.JSONField()),
                ('billed_components', models.JSONField(default=list)),
                ('canonical_request_cost', models.PositiveBigIntegerField()),
                ('state', models.CharField(default='reserved', max_length=16)),
                ('settlement_state', models.CharField(default='open', max_length=16)),
                ('uncertainty_reason', models.CharField(blank=True, default='', max_length=64)),
                ('provider_request_ref', models.CharField(blank=True, default='', max_length=256)),
                ('usage', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='modelpendinggrant',
            name='model_grant_closed_state',
        ),
        migrations.AddConstraint(
            model_name='modelpendinggrant',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'active', 'revoked'])), name='model_grant_closed_state'),
        ),
        migrations.AddIndex(
            model_name='modelbudgetaccount',
            index=models.Index(fields=['deployment_id', 'account_ref'], name='model_budget_account_lookup'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetaccount',
            constraint=models.UniqueConstraint(fields=('deployment_id', 'account_ref', 'window_start', 'window_end'), name='model_budget_account_window'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetaccount',
            constraint=models.CheckConstraint(condition=models.Q(('window_end__gt', models.F('window_start'))), name='model_budget_account_window_order'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetaccount',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__in', ['spend', 'rate', 'concurrency'])), name='model_budget_account_dimension'),
        ),
        migrations.AddField(
            model_name='modelbudgetposting',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='engine.modelbudgetaccount'),
        ),
        migrations.AddField(
            model_name='modelreconciliationobligation',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_obligations', to='engine.modelallocation'),
        ),
        migrations.AddField(
            model_name='modelrequestreservation',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_reservations', to='engine.modelallocation'),
        ),
        migrations.AddField(
            model_name='modelreconciliationobligation',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='engine.modelrequestreservation'),
        ),
        migrations.AddField(
            model_name='modeldispatchlease',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lease', to='engine.modelrequestreservation'),
        ),
        migrations.AddField(
            model_name='modelbudgetposting',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='engine.modelrequestreservation'),
        ),
        migrations.AddIndex(
            model_name='modelrequestreservation',
            index=models.Index(fields=['state', 'settlement_state'], name='model_request_state_scan'),
        ),
        migrations.AddConstraint(
            model_name='modelrequestreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('caller_key_hmac', ''), _negated=True), fields=('allocation', 'grant_epoch', 'operation_id', 'caller_key_hmac'), name='model_request_retry_key'),
        ),
        migrations.AddConstraint(
            model_name='modelrequestreservation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['reserved', 'dispatched', 'settled', 'unknown'])), name='model_request_state'),
        ),
        migrations.AddConstraint(
            model_name='modelrequestreservation',
            constraint=models.CheckConstraint(condition=models.Q(('settlement_state__in', ['open', 'settled', 'unknown_charged'])), name='model_request_settlement_state'),
        ),
        migrations.AddIndex(
            model_name='modelreconciliationobligation',
            index=models.Index(fields=['outcome', 'next_attempt_at'], name='model_reconciliation_scan'),
        ),
        migrations.AddConstraint(
            model_name='modelreconciliationobligation',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['unknown', 'charged', 'settled', 'adjusted'])), name='model_reconciliation_outcome'),
        ),
        migrations.AddConstraint(
            model_name='modeldispatchlease',
            constraint=models.CheckConstraint(condition=models.Q(('transport_status__in', ['dispatching', 'active', 'revoking', 'revoked', 'closed'])), name='model_lease_transport_status'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetposting',
            constraint=models.UniqueConstraint(fields=('reservation', 'account'), name='model_budget_posting_once'),
        ),
        migrations.AddConstraint(
            model_name='modelbudgetposting',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['held', 'settled', 'released'])), name='model_budget_posting_state'),
        ),
    ]
