# Generated by Django 6.0.8 on 2026-09-16 23:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0071_model_workload_budgets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimePluginInstallation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("organization_uuid", models.UUIDField(db_index=True)),
                ("plugin_id", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=64)),
                ("manifest", models.JSONField()),
                ("manifest_digest", models.CharField(max_length=71)),
                ("registry_credentials", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("checking", "Checking compatibility"),
                            ("ready", "Ready"),
                            ("failed", "Installation failed"),
                            ("disabled", "Disabled"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="checking",
                        max_length=16,
                    ),
                ),
                ("probe_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("probe_expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(null=True)),
                ("failure_code", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installed_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_uuid", "plugin_id", "version"), name="runtime_plugin_identity"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["checking", "ready", "failed", "disabled", "retired"])),
                        name="runtime_plugin_state",
                    ),
                ],
            },
        ),
    ]
