# Generated by Django 6.0.8 on 2026-09-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0075_merge_plugin_request_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrequestreservation',
            name='billing_bound',
            field=models.JSONField(default=dict),
        ),
    ]
