# Generated by Django 6.0.8 on 2026-09-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0076_request_billing_bound'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccessCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_epoch', models.PositiveBigIntegerField()),
                ('admitted_subnets', models.JSONField()),
                ('enrollment_hash', models.CharField(blank=True, default='', max_length=64)),
                ('enrollment_expires_at', models.DateTimeField()),
                ('access_hash', models.CharField(blank=True, default='', max_length=64)),
                ('access_expires_at', models.DateTimeField(null=True)),
                ('refresh_hash', models.CharField(blank=True, default='', max_length=64)),
                ('hard_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='engine.modelpendinggrant')),
            ],
        ),
    ]
