# Generated by Django 6.0.8 on 2026-09-17 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0077_guest_model_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="raesartifactsatisfactionbinding",
            name="management_ssh_port",
            field=models.PositiveIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name="raesimagemapping",
            name="management_ssh_port",
            field=models.PositiveIntegerField(
                default=22,
                help_text="Image management SSH port; independent of participant access.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="raesartifactsatisfactionbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("management_ssh_port__gte", 1), ("management_ssh_port__lte", 65535)),
                name="raes_binding_management_port_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raesimagemapping",
            constraint=models.CheckConstraint(
                condition=models.Q(("management_ssh_port__gte", 1), ("management_ssh_port__lte", 65535)),
                name="raes_image_management_port_valid",
            ),
        ),
        migrations.AddField(
            model_name="raesartifactsatisfactionbinding",
            name="management_ssh_username",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="raesimagemapping",
            name="management_ssh_username",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
