# Generated by Django 6.0.8 on 2026-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0078_image_management_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='resource_generation',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
