# Generated by Django 6.0.8 on 2026-09-17 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0079_range_resource_generation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="runtimeplugininstallation",
            index=models.Index(fields=["organization_uuid", "-created_at", "-id"], name="runtime_plugin_admin_page"),
        ),
    ]
