# Generated by Django 6.0.8 on 2026-09-18 02:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0080_runtime_plugin_admin_page"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelSourceRegistry",
            fields=[("organization_uuid", models.UUIDField(primary_key=True, serialize=False))],
        ),
        migrations.CreateModel(
            name="ModelSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("organization_uuid", models.UUIDField(db_index=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelSourceRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revision", models.PositiveBigIntegerField()),
                ("configuration", models.JSONField()),
                ("credential_version", models.UUIDField(null=True)),
                ("credential_reference", models.CharField(blank=True, max_length=1024)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retired_at", models.DateTimeField(null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="engine.modelsource"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="modelsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="model_source_revision_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelsourcerevision",
            constraint=models.UniqueConstraint(fields=("source", "revision"), name="model_source_unique_revision"),
        ),
        migrations.AddConstraint(
            model_name="modelsourcerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="model_source_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelsourcerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["pending", "ready", "failed", "retired"])),
                name="model_source_version_state",
            ),
        ),
    ]
