# Generated by Django 6.0.8 on 2026-09-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0081_model_sources"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="modelallocation",
            name="model_allocation_operation_role",
        ),
        migrations.RemoveConstraint(
            model_name="modeloptionalabsence",
            name="model_optional_operation_role",
        ),
        migrations.AddField(
            model_name="modelaccesscredential",
            name="replacement_grant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="predecessor_credentials",
                to="engine.modelpendinggrant",
            ),
        ),
        migrations.AddField(
            model_name="modelallocation",
            name="source_policy_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modeloptionalabsence",
            name="source_policy_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="range",
            name="model_source_policy_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="modelallocation",
            constraint=models.UniqueConstraint(
                fields=("request_id", "operation_id", "workload_role", "source_policy_revision"),
                name="model_allocation_operation_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="modeloptionalabsence",
            constraint=models.UniqueConstraint(
                fields=("request_id", "operation_id", "workload_role", "source_policy_revision"),
                name="model_optional_operation_role",
            ),
        ),
    ]
