# Generated by Django 6.0.8 on 2026-10-05 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0087_range_account_id_range_organization_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiredFeatureArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=128)),
                ('resolved_version', models.CharField(max_length=128)),
                ('platform', models.CharField(max_length=64)),
                ('recipe_id', models.CharField(max_length=128)),
                ('payload_kind', models.CharField(max_length=16)),
                ('install_policy', models.CharField(max_length=16)),
                ('state', models.CharField(choices=[('acquiring', 'Acquiring'), ('ready', 'Ready'), ('failed', 'Failed')], default='acquiring', max_length=16)),
                ('attempt_id', models.UUIDField(blank=True, null=True)),
                ('attempt_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_expires_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=256)),
                ('retry_not_before', models.DateTimeField(blank=True, null=True)),
                ('storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('byte_count', models.BigIntegerField(blank=True, null=True)),
                ('upstream_ref', models.CharField(blank=True, default='', max_length=512)),
                ('upstream_integrity', models.CharField(blank=True, default='', max_length=128)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_name', 'resolved_version', 'platform'), name='engine_feature_artifact_identity_unique'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'ready'), _negated=True), models.Q(models.Q(('storage_key', ''), _negated=True), models.Q(('sha256', ''), _negated=True), ('byte_count__gt', 0), ('acquired_at__isnull', False)), _connector='OR'), name='engine_feature_artifact_ready_has_identity')],
            },
        ),
    ]
