# Generated by Django 6.0.8 on 2026-10-05 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0087_range_account_id_range_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='range',
            name='vpn_gateway_pool_slot',
        ),
        migrations.CreateModel(
            name='VpnSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.UUIDField()),
                ('server', models.CharField(max_length=63)),
                ('client_id', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16)),
                ('end_reason', models.CharField(blank=True, choices=[('disconnected', 'Disconnected'), ('superseded', 'Superseded by a newer session'), ('revoked', 'Range access no longer valid'), ('lease_expired', 'Server stopped renewing the session')], default='', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('lease_expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_sessions', to='engine.range')),
            ],
            options={
                'db_table': 'engine_vpn_session',
                'indexes': [models.Index(fields=['server', 'state'], name='engine_vpnsession_server_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('range',), name='engine_vpn_session_one_active_per_range')],
            },
        ),
    ]
