# Generated by Django 6.0.8 on 2026-10-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0088_acquired_feature_artifact'),
        ('engine', '0088_vpn_server_pool'),
    ]

    operations = [
    ]
