"""Provider-neutral image bootstrap capabilities (GCE and native EC2)."""

from __future__ import annotations

BOOTSTRAP_STANDARD = "standard"
BOOTSTRAP_PREPROMOTED_DC = "prepromoted-domain-controller"
BOOTSTRAP_PRECONFIGURED_MACHINE_HOST = "preconfigured-machine-host"
PARTICIPANT_READINESS_CONTRACT_V1 = "participant-readiness/v1"
SUPPORTED_PARTICIPANT_READINESS_CONTRACTS = frozenset({PARTICIPANT_READINESS_CONTRACT_V1})
SUPPORTED_BOOTSTRAP_CAPABILITIES = frozenset(
    {BOOTSTRAP_STANDARD, BOOTSTRAP_PREPROMOTED_DC, BOOTSTRAP_PRECONFIGURED_MACHINE_HOST}
)

__all__ = [
    "BOOTSTRAP_PRECONFIGURED_MACHINE_HOST",
    "BOOTSTRAP_PREPROMOTED_DC",
    "BOOTSTRAP_STANDARD",
    "PARTICIPANT_READINESS_CONTRACT_V1",
    "SUPPORTED_BOOTSTRAP_CAPABILITIES",
    "SUPPORTED_PARTICIPANT_READINESS_CONTRACTS",
]
