# Generated by Django 6.0.8 on 2026-09-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0046_scenariomodelneeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="model_launch_scope",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
