# Generated by Django 6.0.8 on 2026-09-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0047_model_launch_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="model_package_digest",
            field=models.CharField(blank=True, default="", max_length=71),
        ),
    ]
