# Generated by Django 6.0.8 on 2026-09-17 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0048_model_package_digest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="raespackagesource",
            name="organization_uuid",
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="raespackagesource",
            name="package_name",
            field=models.SlugField(blank=True, default="", editable=False, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="raespackagesource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization_uuid__isnull", False)),
                fields=("organization_uuid", "package_name"),
                name="tenant_pack_name_unique",
            ),
        ),
    ]
