# Generated by Django 6.0.8 on 2026-09-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0049_tenant_pack_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="model_source_policy_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rangeinstance",
            name="model_sources",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
