# Generated by Django 6.0.8 on 2026-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0050_range_model_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="model_source_policy_error",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="rangeinstance",
            name="model_source_sponsorship",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
