# Generated by Django 6.0.8 on 2026-09-20 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_live_model_source_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeinstance',
            name='account_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rangeinstance',
            name='organization_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rangeinstance',
            name='scope_kind',
            field=models.CharField(blank=True, choices=[('installation', 'Installation'), ('account', 'Account')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='request',
            name='account_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='organization_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='scope_kind',
            field=models.CharField(blank=True, choices=[('installation', 'Installation'), ('account', 'Account')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='rangeinstance',
            name='workspace_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Workspace this range is scoped to (soft reference; see ADR-046).', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='workspace_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Workspace this request was launched in (soft reference; see ADR-046).', null=True),
        ),
        migrations.AddConstraint(
            model_name='rangeinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_id__isnull', True), ('organization_id__isnull', True), ('scope_kind', ''), ('workspace_id__isnull', False)), models.Q(('account_id__isnull', True), ('organization_id__isnull', True), ('scope_kind', 'installation'), ('workspace_id__isnull', True)), models.Q(('account_id__isnull', False), ('scope_kind', 'account'), models.Q(('workspace_id__isnull', True), ('organization_id__isnull', False), _connector='OR')), _connector='OR'), name='cms_range_resource_scope_shape'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_id__isnull', True), ('organization_id__isnull', True), ('scope_kind', ''), ('workspace_id__isnull', False)), models.Q(('account_id__isnull', True), ('organization_id__isnull', True), ('scope_kind', 'installation'), ('workspace_id__isnull', True)), models.Q(('account_id__isnull', False), ('scope_kind', 'account'), models.Q(('workspace_id__isnull', True), ('organization_id__isnull', False), _connector='OR')), _connector='OR'), name='cms_request_resource_scope_shape'),
        ),
    ]
