# Generated by Django 6.0.8 on 2026-09-21 01:05

import uuid

from django.db import migrations, models


def populate_range_ids(apps, schema_editor):
    ranges = apps.get_model("cms", "RangeInstance")
    rows = ranges.objects.using(schema_editor.connection.alias)
    for pk in rows.values_list("pk", flat=True).iterator():
        rows.filter(pk=pk).update(uuid=uuid.uuid5(uuid.NAMESPACE_URL, f"shifter:range:{pk}"))


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0052_rangeinstance_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_range_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="rangeinstance",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
