# Generated by Django 6.0.8 on 2026-09-20 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_model_access_group_eligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('human', 'Human'), ('service', 'Service')], max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_principals', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_service_principals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'management_principal',
            },
        ),
        migrations.CreateModel(
            name='ProviderBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_bindings', to='management.principal')),
            ],
            options={
                'db_table': 'management_provider_binding',
            },
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('human', 'service'))), name='principal_kind_closed'),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_by__isnull', True), ('kind', 'human'), ('responsible_user__isnull', True), ('user__isnull', False)), models.Q(('kind', 'service'), ('user__isnull', True)), _connector='OR'), name='principal_human_service_shape'),
        ),
        migrations.AddConstraint(
            model_name='providerbinding',
            constraint=models.UniqueConstraint(fields=('issuer', 'subject'), name='uniq_provider_principal_tuple'),
        ),
        migrations.AddConstraint(
            model_name='providerbinding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issuer', ''), _negated=True), models.Q(('subject', ''), _negated=True)), name='provider_binding_nonblank_tuple'),
        ),
    ]
