# Generated by Django 6.0.8 on 2026-09-21 00:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0016_provider_binding_immutability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCredentialAdmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("audience", models.URLField(max_length=500)),
                ("scopes", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_admissions",
                        to="management.providerbinding",
                    ),
                ),
            ],
            options={
                "db_table": "management_service_credential_admission",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("binding", "audience"),
                        condition=models.Q(is_active=True),
                        name="unique_active_service_admission",
                    )
                ],
            },
        ),
    ]
