"""Closed Shifter application-authorization contracts."""

from .catalog import (
    ACTION_CATALOG,
    APPLICATION_ADMINISTRATOR_ACTIONS,
    PREDEFINED_POLICIES,
    ActionDefinition,
    AuthorizationContractError,
    PredefinedPolicyDefinition,
    action_definition,
    predefined_policy_definition,
)
from .contracts import (
    AuthorizationDecision,
    AuthorizationRequest,
    CredentialCeiling,
    DecisionKind,
    TargetRef,
)
from .inventory import (
    AuthorizationDescendantResolutionError,
    bind_authorization_descendant_resolver,
    resolve_authorization_descendants,
)
from .port import (
    AuthorizationProvider,
    AuthorizationProviderBindingError,
    bind_authorization_provider_factory,
    configured_authorization_provider,
)
from .relationships import (
    AdministrativeRoleChange,
    AuthorizationProviderError,
    AuthorizationRelationshipChange,
    GroupMembershipChange,
    PolicyEffect,
    PolicyRelationshipChange,
    RelationshipChangePage,
    RelationshipObjectType,
    RelationshipState,
    RelationshipSubject,
    RelationshipTuple,
    RoleAssignmentChange,
    VersionedRelationshipChange,
)

__all__ = [
    "ACTION_CATALOG",
    "APPLICATION_ADMINISTRATOR_ACTIONS",
    "PREDEFINED_POLICIES",
    "ActionDefinition",
    "AdministrativeRoleChange",
    "AuthorizationContractError",
    "AuthorizationDecision",
    "AuthorizationDescendantResolutionError",
    "AuthorizationProvider",
    "AuthorizationProviderBindingError",
    "AuthorizationProviderError",
    "AuthorizationRelationshipChange",
    "AuthorizationRequest",
    "CredentialCeiling",
    "DecisionKind",
    "GroupMembershipChange",
    "PolicyEffect",
    "PolicyRelationshipChange",
    "PredefinedPolicyDefinition",
    "RelationshipChangePage",
    "RelationshipObjectType",
    "RelationshipState",
    "RelationshipSubject",
    "RelationshipTuple",
    "RoleAssignmentChange",
    "TargetRef",
    "VersionedRelationshipChange",
    "action_definition",
    "bind_authorization_descendant_resolver",
    "bind_authorization_provider_factory",
    "configured_authorization_provider",
    "predefined_policy_definition",
    "resolve_authorization_descendants",
]
