# Generated by Django 6.0.8 on 2026-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0024_guest_model_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('apikey', 'API Key'), ('range', 'Range'), ('credential', 'Credential'), ('agent', 'Agent'), ('user', 'User'), ('session', 'Session'), ('ngfw', 'NGFW'), ('config', 'Configuration'), ('experiment', 'Experiment'), ('scenario', 'Scenario'), ('script', 'Script'), ('workspace_membership', 'Workspace Membership'), ('workspace_invitation', 'Workspace Invitation'), ('workspace', 'Workspace'), ('organization', 'Organization'), ('account', 'Account'), ('account_membership', 'Account Membership'), ('principal', 'Principal'), ('provider_binding', 'Provider Binding'), ('communication', 'Communication'), ('sharing_binding', 'Sharing Binding'), ('model_request', 'Model Request'), ('model_credential', 'Model Credential'), ('preparation_adapter', 'Preparation Adapter'), ('runtime_plugin', 'Runtime Plugin'), ('preparation_grant', 'Preparation Grant'), ('artifact_preparation', 'Artifact Preparation')], max_length=20),
        ),
    ]
