# Generated by Django 6.0.8 on 2026-09-21 00:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_credential_ids(apps, schema_editor):
    tokens = apps.get_model("shared", "ApiToken")
    for token in tokens.objects.using(schema_editor.connection.alias).filter(credential_uuid__isnull=True).iterator():
        tokens.objects.using(schema_editor.connection.alias).filter(pk=token.pk).update(
            credential_uuid=uuid.uuid5(uuid.NAMESPACE_URL, f"shifter:personal-credential:{token.pk}")
        )


def map_legacy_owners(apps, schema_editor):
    tokens = apps.get_model("shared", "ApiToken")
    principals = apps.get_model("management", "Principal")
    alias = schema_editor.connection.alias
    for principal in principals.objects.using(alias).filter(kind="human").iterator():
        tokens.objects.using(alias).filter(created_by_id=principal.user_id).update(principal_uuid=principal.uuid)


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0026_alter_auditlog_action_alter_auditlog_entity_type"),
        ("management", "0016_provider_binding_immutability"),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="credential_uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_credential_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="apitoken",
            name="credential_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="knox_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_metadata",
                to=settings.KNOX_TOKEN_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="principal_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(map_legacy_owners, migrations.RunPython.noop),
        migrations.AddField(
            model_name="apitoken",
            name="target_type",
            field=models.CharField(blank=True, default="", editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="target_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="scopes",
            field=models.JSONField(default=list, help_text="Immutable scopes from the central registry"),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="token_id",
            field=models.CharField(help_text="Non-secret display identity", max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="verifier_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
