# Generated by Django 6.0.8 on 2026-09-21 04:35

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def _set_append_profile(apps, schema_editor, version):
    """Change only the future append profile, never historical evidence/digests.

    The migration owner changes the guarded head within this atomic migration.
    The runtime role still cannot change its identity or disable the guard.
    """
    is_postgres = schema_editor.connection.vendor == "postgresql"
    if is_postgres:
        schema_editor.execute("LOCK TABLE public.shared_audit_chain_head IN ACCESS EXCLUSIVE MODE")
        schema_editor.execute(
            "ALTER TABLE public.shared_audit_chain_head DISABLE TRIGGER shared_audit_chain_head_guard"
        )
    apps.get_model("shared", "AuditChainHead").objects.using(schema_editor.connection.alias).filter(singleton=1).update(
        canonicalization_version=version
    )
    if is_postgres:
        schema_editor.execute("ALTER TABLE public.shared_audit_chain_head ENABLE TRIGGER shared_audit_chain_head_guard")


def upgrade_append_profile(apps, schema_editor):
    _set_append_profile(apps, schema_editor, 2)


def downgrade_empty_v2_profile(apps, schema_editor):
    if (
        apps.get_model("shared", "AuditLog")
        .objects.using(schema_editor.connection.alias)
        .filter(canonicalization_version__gte=2)
        .exists()
    ):
        raise IrreversibleError("Cannot discard principal attribution after v2 audit evidence has been committed")
    _set_append_profile(apps, schema_editor, 1)


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0028_personal_credential_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_principal_uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditchainhead",
            name="canonicalization_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("apikey", "API Key"),
                    ("system", "System"),
                    ("cognito", "Cognito"),
                    ("principal", "Principal"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="canonicalization_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.RunPython(upgrade_append_profile, downgrade_empty_v2_profile),
    ]
